
spring.application.name=auth-api
server.port=8080


spring.datasource.url=jdbc:postgresql://localhost:5432/khatascandev
spring.datasource.username=postgres
spring.datasource.password=007
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# = MYSQL CONFIG (DEV)
# ===============================
#spring.datasource.url=jdbc:mysql://localhost:3306/auth_api?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=Pravin@2024
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ===============================
# = JPA
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false


app.jwt.secret=${JWT_SECRET:local-dev-secret-change-me}
app.jwt.secret.expiration-ms=86400000
